substitutions:
  devicename: "p1s-bentobox"
  upper_devicename: "P1S BentoBox"
  platsa_sensor_version: 0.0.1

esphome:
  name: "${devicename}"
  friendly_name: "${upper_devicename}"
  name_add_mac_suffix: false  # Set to false if you don't want part of the MAC address in the name

esp8266:
  board: esp01_1m

# Enable Home Assistant API
api:

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  # Defaults to device name with no password
  ap: {}

captive_portal:

uart:
  - rx_pin: GPIO3 # Pin 30 or RX
    tx_pin: GPIO1  # Pin 31 or TX
    baud_rate: 9600
    id: pms5003_uart

i2c:
  # https://esphome.io/components/i2c.html
  sda: GPIO5
  scl: GPIO4
  frequency: 400kHz  # 400kHz eliminates warnings about components taking a long time other than SGP40 component: https://github.com/esphome/issues/issues/4717

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_dbm
    update_interval: 60s

  - platform: uptime
    name: "Uptime"
    id: device_uptime
    update_interval: 10s
  
  - platform: sht4x
    # SHT40 https://esphome.io/components/sensor/sht4x.html
    temperature:
      name: "Temperature"
      id: temp
    humidity:
      name: "Humidity"
      id: humidity
    address: 0x44
  
  - platform: sgp4x
    # SGP41 https://esphome.io/components/sensor/sgp4x.html
    voc:
      name: "VOC Index"
      id: voc
    nox:
      name: "NOx Index"
      id: nox
    compensation:  # Remove this block if no temp/humidity sensor present for compensation
      temperature_source: temp
      humidity_source: humidity
  - platform: pmsx003
    # PMS5003 https://esphome.io/components/sensor/pmsx003.html
    # Update every 2 minutes to attempt to extend life, but could impact accuracy of readings in device
    type: PMSX003
    uart_id: pms5003_uart
    pm_2_5:
      name: "PM 2.5"
      id: pm_2_5
    pm_1_0:
      name: "PM 1.0"
      id: pm_1_0
    pm_10_0:
      name: "PM 10.0"
      id: pm_10_0
    pm_0_3um:
      name: "PM 0.3"
      id: pm_0_3um
    update_interval: 2min
# Fan Speed
  - platform: pulse_counter
    pin:
      number: GPIO13
      mode:
        input: true
        pullup: true
    name: PWM Fan RPM
    id: fan_pulse
    unit_of_measurement: 'RPM'
    filters:
      - multiply: 0.5
    count_mode:
      rising_edge: INCREMENT
      falling_edge: DISABLE
    update_interval: 3s
#switch: 
#  - platform: gpio
#    name: "Lights"
#    pin: GPIO15
output:
  - platform: esp8266_pwm
    pin: GPIO12
    frequency: 10000 Hz
    id: pwm_fan
  - platform: esp8266_pwm
    pin: GPIO0
    frequency: 10000 Hz
    id: fanhub_pwm
fan:
  - platform: speed
    output: pwm_fan
    name: "Fan"
#  - platform: speed
#    output: fanhub_pwm
#    name: "PWM Ecnlosure Fan"